ARG BASE_IMAGE_TAG=python3.12-bookworm-slim
FROM ghcr.io/astral-sh/uv:${BASE_IMAGE_TAG}

# FROM python:3-slim-bullseye
# FROM ../python:3.14.3-dev
# USER root
# RUN pip install kubernetes --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
# RUN pip install prometheus-client --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
# RUN pip install hvac --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org

